# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover_url', models.URLField()),
                ('rating', models.FloatField()),
                ('season', models.IntegerField(default=1)),
                ('episode', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
