# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvshow',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AddField(
            model_name='tvshow',
            name='last_seen',
            field=models.DateField(auto_now=True),
        ),
    ]
