# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20170115_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='last_seen',
            field=models.DateField(default=frontend.models.unix0),
        ),
    ]
