# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20170115_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='trailer',
            new_name='trailer_url',
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='tagline',
            field=models.TextField(blank=True, default='No tagline.'),
        ),
    ]
