# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20170505_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=2023, null=True),
        ),
    ]
