# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20180422_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
