# Generated by Django 4.0 on 2021-12-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_rename_imdb_id_tvshow_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='movie_db',
            field=models.CharField(default='imdb', max_length=30),
        ),
    ]
