# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('when', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-when', 'subject'],
            },
        ),
    ]
